name: Daily Album Feed

on:
  schedule:
    # Run every day at 11:55 UTC = 7:55am ET
    - cron: "55 11 * * *"
  workflow_dispatch:  # Allow manual runs too

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run album feed script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python album_feed.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.xml
          git commit -m "Daily album update" || echo "No changes to commit"
          git push
